executable = env/bin/python
filename = mcl_toolbox/calculate_strategy_scores.py
arguments = $(filename) $(exp_num:scarcity_scarce) $(num_simulations:100000) $(click_cost:0.25)
output = log/strategy_scores/scarcity_scarce/output.stdout
error  = log/strategy_scores/scarcity_scarce/output.stderr
log   = log/strategy_scores/scarcity_scarce/output.log
request_memory = 20000
request_cpus = 1

queue

executable = env/bin/python
filename = mcl_toolbox/calculate_strategy_scores.py
arguments = $(filename) $(exp_num:scarcity_control) $(num_simulations:100000) $(click_cost:1)
output = log/strategy_scores/scarcity_control/output.stdout
error  = log/strategy_scores/scarcity_control/output.stderr
log   = log/strategy_scores/scarcity_control/output.log
request_memory = 20000
request_cpus = 1

queue