executable = env/bin/python
filename = mcl_toolbox/fit_mcrl_models.py
arguments = $(filename) $(exp_num:scarcity_scarce) $(optimization_criterion:likelihood) $(pid) $(num_trials:120) "{\"optimization_params\":{\"learn_from_actions\":1,\"max_integration_degree\":7}}"
output = log/fit_models/1.1/scarce/$(pid).stdout
error  = log/fit_models/1.1/scarce/$(pid).stderr
log   = log/fit_models/1.1/scarce/$(pid).log
request_memory = 20000
request_cpus = 1

queue pid from scarce_pids.txt