executable = env/bin/python
filename = mcl_toolbox/infer_sequences.py
arguments = $(filename) $(exp_num:scarcity_scarce) $(num_trials:120)
output = log/infer_strategies/scarcity_scarce/output.stdout
error  = log/infer_strategies/scarcity_scarce/output.stderr
log   = log/infer_strategies/scarcity_scarce/output.log
request_memory = 50000
request_cpus = 1

queue

executable = env/bin/python
filename = mcl_toolbox/infer_sequences.py
arguments = $(filename) $(exp_num:scarcity_control) $(num_trials:30)
output = log/infer_strategies/scarcity_scarce/output.stdout
error  = log/infer_strategies/scarcity_scarce/output.stderr
log   = log/infer_strategies/scarcity_scarce/output.log
request_memory = 50000
request_cpus = 1

queue